import { useEffect,useState,type FormEvent } from 'react';
import { useAuth } from '../auth/AuthContext';

type Company={_id:string;name:string};type Branch={_id:string;name:string;companyId:Company|string};type Party={_id:string;name:string;companyId:Company|string};type Product={_id:string;name:string;sku:string;cost:number;companyId:Company|string};type Entry={_id:string;type:'income'|'expense';category:string;amount:number;description:string};type Doc={_id:string;total:number;createdAt:string};

export const CommercialPage=()=>{const {user,api}=useAuth();const perms=new Set(user?.roles.flatMap(r=>r.permissions)??[]);const can=(p:string)=>perms.has('*')||perms.has(p);
const [companies,setCompanies]=useState<Company[]>([]),[branches,setBranches]=useState<Branch[]>([]),[customers,setCustomers]=useState<Party[]>([]),[suppliers,setSuppliers]=useState<Party[]>([]),[products,setProducts]=useState<Product[]>([]),[sales,setSales]=useState<Doc[]>([]),[purchases,setPurchases]=useState<Doc[]>([]),[finance,setFinance]=useState<{entries:Entry[];summary:{income:number;expense:number;balance:number}}>({entries:[],summary:{income:0,expense:0,balance:0}}),[error,setError]=useState('');
const [sale,setSale]=useState({companyId:'',branchId:'',customerId:'',productId:'',quantity:1}),[purchase,setPurchase]=useState({companyId:'',branchId:'',supplierId:'',productId:'',quantity:1,unitCost:0}),[entry,setEntry]=useState({companyId:'',branchId:'',type:'expense' as 'income'|'expense',category:'',description:'',amount:0});
const [saving,setSaving]=useState<string|null>(null),[success,setSuccess]=useState('');
const load=async()=>{try{setError('');const cs=await api<Company[]>('/companies');const first=cs[0]?._id??'';setCompanies(cs);setBranches(await api<Branch[]>('/branches'));setCustomers(can('customers.read')?await api<Party[]>('/customers'):[]);setSuppliers(can('suppliers.read')?await api<Party[]>('/suppliers'):[]);setProducts(can('products.read')?await api<Product[]>('/products'):[]);setSale(x=>({...x,companyId:x.companyId||first}));setPurchase(x=>({...x,companyId:x.companyId||first}));setEntry(x=>({...x,companyId:x.companyId||first}));if(can('sales.read'))setSales(await api<Doc[]>('/sales'));if(can('purchases.read'))setPurchases(await api<Doc[]>('/purchases'));if(can('finance.read'))setFinance(await api<{entries:Entry[];summary:{income:number;expense:number;balance:number}}>('/finance'));}catch(e){setError(e instanceof Error?e.message:'Error al cargar')}};
useEffect(()=>{void load()},[api]);
const post=async(e:FormEvent,path:string,data:object,kind:'sale'|'purchase'|'finance')=>{e.preventDefault();if(saving)return;try{setError('');setSuccess('');setSaving(kind);await api(path,{method:'POST',body:JSON.stringify(data)});
if(kind==='sale'){setSale(x=>({...x,customerId:'',productId:'',quantity:1}));setSuccess('Venta registrada correctamente. Inventario y finanzas fueron actualizados.')}
if(kind==='purchase'){setPurchase(x=>({...x,supplierId:'',productId:'',quantity:1,unitCost:0}));setSuccess('Compra registrada correctamente. Inventario y finanzas fueron actualizados.')}
if(kind==='finance'){setEntry(x=>({...x,category:'',description:'',amount:0}));setSuccess('Movimiento financiero registrado correctamente.')}
await load()}catch(x){setError(x instanceof Error?x.message:'Error al guardar')}finally{setSaving(null)}};
const options=companies.map(x=><option key={x._id} value={x._id}>{x.name}</option>);const match=(x:{companyId:Company|string},id:string)=>(typeof x.companyId==='string'?x.companyId:x.companyId._id)===id;
return <section><div className="page-heading"><div><span className="eyebrow">Fase 4</span><h1>Ventas, compras y finanzas</h1><p>Movimientos comerciales conectados automáticamente con inventario y flujo financiero.</p></div></div>{error&&<p className="form-error">{error}</p>}{success&&<p className="form-success">{success}</p>}
{can('finance.read')&&<div className="finance-summary"><article><span>Ingresos</span><strong>$ {finance.summary.income.toFixed(2)}</strong></article><article><span>Egresos</span><strong>$ {finance.summary.expense.toFixed(2)}</strong></article><article><span>Balance</span><strong>$ {finance.summary.balance.toFixed(2)}</strong></article></div>}
<div className="operations-grid">
{can('sales.create')&&<form className="info-card admin-form" onSubmit={e=>void post(e,'/sales',sale,'sale')}><h2>Nueva venta</h2><label>Empresa<select value={sale.companyId} onChange={e=>setSale({...sale,companyId:e.target.value,branchId:'',customerId:'',productId:''})}>{options}</select></label><label>Sucursal<select required value={sale.branchId} onChange={e=>setSale({...sale,branchId:e.target.value})}><option value="">Sucursal</option>{branches.filter(x=>match(x,sale.companyId)).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></label><label>Cliente (opcional)<select value={sale.customerId} onChange={e=>setSale({...sale,customerId:e.target.value})}><option value="">Cliente opcional</option>{customers.filter(x=>match(x,sale.companyId)).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></label><label>Producto<select required value={sale.productId} onChange={e=>setSale({...sale,productId:e.target.value})}><option value="">Producto</option>{products.filter(x=>match(x,sale.companyId)).map(x=><option key={x._id} value={x._id}>{x.name} · {x.sku}</option>)}</select></label><label>Cantidad<input type="number" min="1" value={sale.quantity} onChange={e=>setSale({...sale,quantity:Number(e.target.value)})}/></label><button className="primary-button" disabled={saving!==null}>{saving==='sale'?'Registrando…':'Registrar venta'}</button></form>}
{can('purchases.create')&&<form className="info-card admin-form" onSubmit={e=>void post(e,'/purchases',purchase,'purchase')}><h2>Nueva compra</h2><label>Empresa<select value={purchase.companyId} onChange={e=>setPurchase({...purchase,companyId:e.target.value,branchId:'',supplierId:'',productId:''})}>{options}</select></label><label>Sucursal<select required value={purchase.branchId} onChange={e=>setPurchase({...purchase,branchId:e.target.value})}><option value="">Sucursal</option>{branches.filter(x=>match(x,purchase.companyId)).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></label><label>Proveedor (opcional)<select value={purchase.supplierId} onChange={e=>setPurchase({...purchase,supplierId:e.target.value})}><option value="">Proveedor opcional</option>{suppliers.filter(x=>match(x,purchase.companyId)).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></label><label>Producto<select required value={purchase.productId} onChange={e=>{const p=products.find(x=>x._id===e.target.value);setPurchase({...purchase,productId:e.target.value,unitCost:p?.cost??0})}}><option value="">Producto</option>{products.filter(x=>match(x,purchase.companyId)).map(x=><option key={x._id} value={x._id}>{x.name} · {x.sku}</option>)}</select></label><div className="form-row"><label>Cantidad<input type="number" min="1" value={purchase.quantity} onChange={e=>setPurchase({...purchase,quantity:Number(e.target.value)})}/></label><label>Costo unitario ($)<input type="number" min="0" step="0.01" value={purchase.unitCost} onChange={e=>setPurchase({...purchase,unitCost:Number(e.target.value)})}/></label></div><button className="primary-button" disabled={saving!==null}>{saving==='purchase'?'Registrando…':'Registrar compra'}</button></form>}
{can('finance.create')&&<form className="info-card admin-form" onSubmit={e=>void post(e,'/finance',entry,'finance')}><h2>Movimiento manual</h2><label>Empresa<select value={entry.companyId} onChange={e=>setEntry({...entry,companyId:e.target.value,branchId:''})}>{options}</select></label><label>Sucursal<select required value={entry.branchId} onChange={e=>setEntry({...entry,branchId:e.target.value})}><option value="">Selecciona una sucursal</option>{branches.filter(x=>match(x,entry.companyId)).map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select></label><label>Tipo<select value={entry.type} onChange={e=>setEntry({...entry,type:e.target.value as 'income'|'expense'})}><option value="income">Ingreso</option><option value="expense">Egreso</option></select></label><label>Categoría<input required placeholder="Ej. Renta, servicio, ajuste" value={entry.category} onChange={e=>setEntry({...entry,category:e.target.value})}/></label><label>Descripción<input placeholder="Detalle del movimiento" value={entry.description} onChange={e=>setEntry({...entry,description:e.target.value})}/></label><label>Monto ($)<input required type="number" min="0.01" step="0.01" value={entry.amount} onChange={e=>setEntry({...entry,amount:Number(e.target.value)})}/></label><button className="primary-button" disabled={saving!==null}>{saving==='finance'?'Guardando…':'Guardar movimiento'}</button></form>}
</div><div className="operations-grid">{can('sales.read')&&<div className="info-card"><h2>Ventas recientes</h2><div className="data-list">{sales.map(x=><article key={x._id}><strong>Venta</strong><b>$ {x.total.toFixed(2)}</b></article>)}</div></div>}{can('purchases.read')&&<div className="info-card"><h2>Compras recientes</h2><div className="data-list">{purchases.map(x=><article key={x._id}><strong>Compra</strong><b>$ {x.total.toFixed(2)}</b></article>)}</div></div>}{can('finance.read')&&<div className="info-card"><h2>Movimientos financieros</h2><div className="data-list">{finance.entries.map(x=><article key={x._id}><div><strong>{x.category}</strong><span>{x.description}</span></div><b>{x.type==='income'?'+':'-'} $ {x.amount.toFixed(2)}</b></article>)}</div></div>}</div></section>};
