import { useEffect, useState, type FormEvent } from 'react';
import { useAuth } from '../auth/AuthContext';

const API=import.meta.env.VITE_API_URL??'http://localhost:4000/api/v1';
type Company={_id:string;name:string}; type Branch={_id:string;name:string;companyId:Company|string};
type Party={_id:string;name:string;email?:string;phone?:string;companyId:Company|string};
type Product={_id:string;name:string;sku:string;price:number;minStock:number;companyId:Company|string};
type Stock={_id:string;quantity:number;branchId:{name:string;code:string};productId:{name:string;sku:string;minStock:number}};
const api=async(path:string,init:RequestInit={})=>{const r=await fetch(`${API}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${sessionStorage.getItem('jafora.access')}`,...init.headers}});const b=await r.json();if(!r.ok)throw new Error(b.message??'Error de comunicación');return b.data;};

export const CoreOperationsPage=()=>{
 const {user}=useAuth(); const perms=new Set(user?.roles.flatMap(r=>r.permissions)??[]); const can=(p:string)=>perms.has('*')||perms.has(p);
 const [companies,setCompanies]=useState<Company[]>([]),[branches,setBranches]=useState<Branch[]>([]),[customers,setCustomers]=useState<Party[]>([]),[suppliers,setSuppliers]=useState<Party[]>([]),[products,setProducts]=useState<Product[]>([]),[stocks,setStocks]=useState<Stock[]>([]),[error,setError]=useState('');
 const [customer,setCustomer]=useState({companyId:'',name:'',email:'',phone:'',taxId:'',address:''});
 const [supplier,setSupplier]=useState({...customer}); const [product,setProduct]=useState({companyId:'',sku:'',name:'',category:'',cost:0,price:0,minStock:0}); const [stock,setStock]=useState({companyId:'',branchId:'',productId:'',quantity:0});
 const load=async()=>{try{setError('');const cs=await api('/companies');setCompanies(cs);const first=cs[0]?._id??'';setCustomer(x=>({...x,companyId:x.companyId||first}));setSupplier(x=>({...x,companyId:x.companyId||first}));setProduct(x=>({...x,companyId:x.companyId||first}));setStock(x=>({...x,companyId:x.companyId||first}));setBranches(await api('/branches'));if(can('customers.read'))setCustomers(await api('/customers'));if(can('suppliers.read'))setSuppliers(await api('/suppliers'));if(can('products.read'))setProducts(await api('/products'));if(can('inventory.read'))setStocks(await api('/inventory'));}catch(e){setError(e instanceof Error?e.message:'Error al cargar datos');}};
 useEffect(()=>{void load();},[]);
 const submit=async(e:FormEvent,path:string,data:object,reset:()=>void)=>{e.preventDefault();try{await api(path,{method:'POST',body:JSON.stringify(data)});reset();await load();}catch(x){setError(x instanceof Error?x.message:'No fue posible guardar');}};
 const setQty=async(e:FormEvent)=>{e.preventDefault();try{await api('/inventory',{method:'PUT',body:JSON.stringify(stock)});await load();}catch(x){setError(x instanceof Error?x.message:'No fue posible actualizar inventario');}};
 const companyOptions=companies.map(c=><option key={c._id} value={c._id}>{c.name}</option>);
 return <section><div className="page-heading"><div><span className="eyebrow">Fase 3</span><h1>Operaciones maestras</h1><p>Clientes, proveedores, productos e inventario centralizados por empresa.</p></div></div>{error&&<p className="form-error">{error}</p>}
 <div className="operations-grid">
 {can('customers.create')&&<form className="info-card admin-form" onSubmit={e=>void submit(e,'/customers',customer,()=>setCustomer(x=>({...x,name:'',email:'',phone:'',taxId:'',address:''})))}><h2>Nuevo cliente</h2><select value={customer.companyId} onChange={e=>setCustomer({...customer,companyId:e.target.value})}>{companyOptions}</select><input placeholder="Nombre" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} required/><input placeholder="Correo" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/><input placeholder="Teléfono" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/><button className="primary-button">Crear cliente</button></form>}
 {can('suppliers.create')&&<form className="info-card admin-form" onSubmit={e=>void submit(e,'/suppliers',supplier,()=>setSupplier(x=>({...x,name:'',email:'',phone:'',taxId:'',address:''})))}><h2>Nuevo proveedor</h2><select value={supplier.companyId} onChange={e=>setSupplier({...supplier,companyId:e.target.value})}>{companyOptions}</select><input placeholder="Nombre" value={supplier.name} onChange={e=>setSupplier({...supplier,name:e.target.value})} required/><input placeholder="Correo" value={supplier.email} onChange={e=>setSupplier({...supplier,email:e.target.value})}/><input placeholder="Teléfono" value={supplier.phone} onChange={e=>setSupplier({...supplier,phone:e.target.value})}/><button className="primary-button">Crear proveedor</button></form>}
 {can('products.create')&&<form className="info-card admin-form" onSubmit={e=>void submit(e,'/products',product,()=>setProduct(x=>({...x,sku:'',name:'',category:'',cost:0,price:0,minStock:0})))}><h2>Nuevo producto</h2><select value={product.companyId} onChange={e=>setProduct({...product,companyId:e.target.value})}>{companyOptions}</select><input placeholder="SKU" value={product.sku} onChange={e=>setProduct({...product,sku:e.target.value})} required/><input placeholder="Nombre" value={product.name} onChange={e=>setProduct({...product,name:e.target.value})} required/><input placeholder="Categoría" value={product.category} onChange={e=>setProduct({...product,category:e.target.value})}/><div className="form-row"><input type="number" min="0" placeholder="Costo" value={product.cost} onChange={e=>setProduct({...product,cost:Number(e.target.value)})}/><input type="number" min="0" placeholder="Precio" value={product.price} onChange={e=>setProduct({...product,price:Number(e.target.value)})}/><input type="number" min="0" placeholder="Stock mín." value={product.minStock} onChange={e=>setProduct({...product,minStock:Number(e.target.value)})}/></div><button className="primary-button">Crear producto</button></form>}
 {can('inventory.update')&&<form className="info-card admin-form" onSubmit={setQty}><h2>Actualizar existencia</h2><select value={stock.companyId} onChange={e=>setStock({...stock,companyId:e.target.value,branchId:'',productId:''})}>{companyOptions}</select><select value={stock.branchId} onChange={e=>setStock({...stock,branchId:e.target.value})}><option value="">Sucursal</option>{branches.filter(b=>(typeof b.companyId==='string'?b.companyId:b.companyId._id)===stock.companyId).map(b=><option key={b._id} value={b._id}>{b.name}</option>)}</select><select value={stock.productId} onChange={e=>setStock({...stock,productId:e.target.value})}><option value="">Producto</option>{products.filter(p=>(typeof p.companyId==='string'?p.companyId:p.companyId._id)===stock.companyId).map(p=><option key={p._id} value={p._id}>{p.name} · {p.sku}</option>)}</select><input type="number" min="0" value={stock.quantity} onChange={e=>setStock({...stock,quantity:Number(e.target.value)})}/><button className="primary-button">Guardar existencia</button></form>}
 </div>
 <div className="operations-grid">
 {can('customers.read')&&<div className="info-card"><h2>Clientes</h2><div className="data-list">{customers.map(x=><article key={x._id}><div><strong>{x.name}</strong><span>{x.email||'Sin correo'} · {x.phone||'Sin teléfono'}</span></div></article>)}</div></div>}
 {can('suppliers.read')&&<div className="info-card"><h2>Proveedores</h2><div className="data-list">{suppliers.map(x=><article key={x._id}><div><strong>{x.name}</strong><span>{x.email||'Sin correo'} · {x.phone||'Sin teléfono'}</span></div></article>)}</div></div>}
 {can('products.read')&&<div className="info-card"><h2>Productos</h2><div className="data-list">{products.map(x=><article key={x._id}><div><strong>{x.name}</strong><span>{x.sku} · ${x.price.toFixed(2)}</span></div></article>)}</div></div>}
 {can('inventory.read')&&<div className="info-card"><h2>Inventario</h2><div className="data-list">{stocks.map(x=><article key={x._id}><div><strong>{x.productId.name}</strong><span>{x.branchId.name} · {x.quantity} unidades</span></div><b>{x.quantity<=x.productId.minStock?'Stock bajo':'Disponible'}</b></article>)}</div></div>}
 </div></section>;
};
